name: Annoyance report
description: 'Use this template to report a bug'
title: "[ANN]: "
labels: ["annoyance"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this annoyance report!
  - type: textarea
    id: describe-annoyance
    attributes:
      label: Describe the annoyance
      description: 'A clear and concise description of what the annoyance is.'
      placeholder: Why it's too hard to set limits to user? Like, ...
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: Here you can suggest how it can be fixed. Maybe some thing is hard to do? How do you see it should be done?
      placeholder: 'What about some command like...'
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context.
      placeholder: ...
  - type: checkboxes
    id: terms
    attributes:
      label: Checkboxes
      description: Please agree with following statements
      options:
        - label: I am sure that this is annoying
          required: true
        - label: I am sure that it is not an error, a bug or mistake
          required: true
        - label: This is so annoying that I am ready to be a Karen and demanding a reward!!!