name: Bug report
description: 'Use this template to report a bug'
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: describe-error-or-mistake
    attributes:
      label: Describe the error/mistake
      description: 'A clear and concise description of what the bug is. For example, "I cannot see our married pairs in our chat", "I cannot warn anyone" and etc. If bot clearly says that error happened and you should report it OR you found translation mistakes (or in docs f.e.) please use "Error/mistake report" template.'
      placeholder: I can't send marry request!
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide step-by-step instruction how to reproduce this bug
      placeholder: '1. Go to... 2. Do... [...] X. There it is'
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context.
      placeholder: ...
  - type: checkboxes
    id: terms
    attributes:
      label: Checkboxes
      description: Please agree with following statements
      options:
        - label: I am sure that I am reporting bug
          required: true
        - label: I am sure that it is not an error or a mistake
          required: true
